name: QA Quick Deploy
on:
  workflow_dispatch:
permissions:
  contents: read
env:
  TZ: Asia/Tokyo
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: qa
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Rebuild recommend.json (full)
        run: node scripts/rebuild-recommend.mjs

      - name: Filter recommend.json to <= today (JST)
        shell: bash
        run: |
          node -e 'const fs=require("fs");const p="public/recommend.json";const d=JSON.parse(fs.readFileSync(p,"utf8"));const arr=Array.isArray(d)?d:(d.items||[]);const t=new Date().toISOString().slice(0,10);const out=arr.filter(x=>(x.date||"")<=t);fs.writeFileSync(p,JSON.stringify(out,null,2));'

      - name: Generate pages
        working-directory: public
        run: node generate-recommend-pages.js

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Sync to QA S3
        env:
          QA_BUCKET: ${{ secrets.S3_BUCKET_QA }}
        shell: bash
        run: |
          if [ -n "$QA_BUCKET" ]; then
            aws s3 sync public "s3://${QA_BUCKET}/" --delete \
              --exclude "*" \
              --include "recommend.json" \
              --include "updates.json" \
              --include "recommend.html" \
              --include "recommend_pages/*"
          else
            echo "skip: S3_BUCKET_QA is empty"
          fi

      - name: Invalidate QA CloudFront
        env:
          QA_CF_ID: ${{ secrets.CF_DISTRIBUTION_ID_QA }}
        shell: bash
        run: |
          if [ -n "$QA_CF_ID" ]; then
            L=$(TZ=Asia/Tokyo date +%F)
            aws cloudfront create-invalidation --distribution-id "$QA_CF_ID" \
              --paths "/updates.json" "/recommend.json" "/recommend_pages/recommend-$L.html" "/recommend.html"
          else
            echo "skip: CF_DISTRIBUTION_ID_QA is empty"
          fi

      - name: Trigger QA notify
        env:
          QA_NOTIFY_URL: ${{ secrets.QA_NOTIFY_URL }}
          QA_NOTIFY_TOKEN: ${{ secrets.QA_NOTIFY_TOKEN }}
        shell: bash
        run: |
          if [ -n "$QA_NOTIFY_URL" ] && [ -n "$QA_NOTIFY_TOKEN" ]; then
            curl -fSs -X POST "$QA_NOTIFY_URL/admin/notify-send?token=$QA_NOTIFY_TOKEN"
          else
            echo "skip: QA_NOTIFY_URL or QA_NOTIFY_TOKEN is empty"
          fi
