name: QA Quick Deploy
on: workflow_dispatch

permissions:
  contents: read

env:
  TZ: Asia/Tokyo

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22" }

      - name: Ingest (no commit)
        run: node scripts/ingest-today.mjs

      - name: Update updates.json (no commit)
        run: node scripts/update-updates-json.mjs

      - name: Generate pages
        working-directory: public
        run: node generate-recommend-pages.js

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Diagnostics (whoami & list QA bucket)
        run: |
          aws sts get-caller-identity
          aws configure list
          aws s3 ls "s3://${{ secrets.S3_BUCKET_QA }}/" || true

      - name: Sync to QA S3
        run: |
          aws s3 sync public s3://${{ secrets.S3_BUCKET_QA }}/ --delete \
            --exclude "*" \
            --include "recommend.json" \
            --include "updates.json" \
            --include "recommend.html" \
            --include "recommend_pages/*"

      - name: Invalidate QA CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CF_DISTRIBUTION_ID_QA }}" \
            --paths "/*"
