name: QA Scheduled Deploy & Notify (v2)
on:
  schedule:
    - cron: '10 22 * * *'
  workflow_dispatch:
permissions:
  contents: read
env:
  TZ: Asia/Tokyo
jobs:
  qa-scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: qa
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Rebuild recommend.json (guarded)
        run: |
          if [ -f scripts/rebuild-recommend.mjs ]; then
            node scripts/rebuild-recommend.mjs
          else
            echo "skip: scripts/rebuild-recommend.mjs is missing"
          fi
